app = "problems-validator"
primary_region = "ams" # Change this to your preferred region

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[mounts]]
  source = "mysql_data"
  destination = "/var/lib/mysql"

[env]
  DEBUG = "False"
  MYSQL_DATABASE = "problems_validator"
  MYSQL_USER = "user"
  MYSQL_PASSWORD = "123"
  DATABASE_URL = "mysql://user:123@localhost:3306/problems_validator"
  CREATE_SUPERUSER = "True"
